### ISSUE TITLE
Melting Point, Boiling Point, and density properties of chemicals

### ISSUE THREAD

**Issue by bhargavakula01** [althonos/pubchem.rs#9]
Hey! 

My name is Bhargav Akula and I am very interested in using this crate for my own project and was wondering if there is going to be an update to the repo where one can get the melting point, boiling point, and density property information for chemicals.

**Comment by althonos** [comment]
Hi @bhargavakula01 ! I had a look and I am not sure this is possible, as the melting point, boiling point and other properties are actually part of the "Experimental Properties" of each PubChem record, and this doesn't seem to be obtainable through the [REST API](https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest) of PubChem...

**Comment by bhargavakula01** [comment]
Ahh that makes sense. Thanks for the information!
